language: generic
dist: xenial

# Does not work
#addons: 
#  apt: 
#    packages: 
#      - singularity-container

install:
  # Singularity prerequisited
  - sudo apt-get install --yes libarchive-dev
  #- sudo apt-get update && sudo apt-get install -y \
  #  build-essential \
  #  libssl-dev \
  #  uuid-dev \
  #  libgpgme11-dev \
  #  squashfs-tools \
  #  wget \
  #  git
  # Install Singularity
  - git clone https://github.com/sylabs/singularity.git
  - cd singularity
  - git fetch --all
  - git checkout 2.5.0
  - ./autogen.sh
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
  - cd ..
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

script:
  # Singularity
  - singularity --version
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links
